package com.artemonre.onemoretodolist.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// background/surface must stay in a mid-tone band (~75-90% lightness in light themes,
// mirrored ~10-25% in dark themes) - components like NeumorphicSegmentedControl derive
// light+dark shadow pairs from this color via simple lerp-toward-white/black, which needs
// real headroom on both sides to read. A background too close to pure white/black makes one
// side of any such pair invisible, no matter how the blend math is tuned. Test new palettes
// against this before adding them.

val LightColorSchemeDefault = lightColorScheme(
    primary = Color(0xFF133665),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF506DA0),
    onPrimaryContainer = Color(0xFFFFFFFF),
    secondary = Color(0xFF2E3647),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF646D80),
    onSecondaryContainer = Color(0xFFFFFFFF),
    tertiary = Color(0xFF452E4A),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF7F6484),
    onTertiaryContainer = Color(0xFFFFFFFF),
    background = Color(0xFFDFE2EC),
    onBackground = Color(0xFF191C20),
    surface = Color(0xFFDFE2EC),
    onSurface = Color(0xFF0F1116),
    surfaceVariant = Color(0xFFE0E2EC),
    onSurfaceVariant = Color(0xFF33363E),
    surfaceDim = Color(0xFF9AA3C6),
    surfaceBright = Color(0xFFECEEF3),
    surfaceContainerLowest = Color(0xFFF6F6F9),
    surfaceContainerLow = Color(0xFFD0D3E2),
    surfaceContainer = Color(0xFFC2C7DB),
    surfaceContainerHigh = Color(0xFFB5BBD4),
    surfaceContainerHighest = Color(0xFFA8AFCD),
    outline = Color(0xFF4F525A),
    error = Color(0xFF740006),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFCF2C27),
    onErrorContainer = Color(0xFFFFFFFF)
)

val DarkColorSchemeDefault = darkColorScheme(
    primary = Color(0xFFCDDDFF),
    onPrimary = Color(0xFF002551),
    primaryContainer = Color(0xFF7491C7),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFFD4DCF2),
    onSecondary = Color(0xFF1D2636),
    secondaryContainer = Color(0xFF8891A5),
    onSecondaryContainer = Color(0xFF000000),
    tertiary = Color(0xFFF3D2F7),
    onTertiary = Color(0xFF331D39),
    tertiaryContainer = Color(0xFFA487A9),
    onTertiaryContainer = Color(0xFF000000),
    background = Color(0xFF1E2024),
    onBackground = Color(0xFFE2E2E9),
    surface = Color(0xFF1E2024),
    onSurface = Color(0xFFFFFFFF),
    surfaceVariant = Color(0xFF44474E),
    onSurfaceVariant = Color(0xFFDADCE6),
    surfaceDim = Color(0xFF1A1B1F),
    surfaceBright = Color(0xFF474D5C),
    surfaceContainerLowest = Color(0xFF121416),
    surfaceContainerLow = Color(0xFF25272C),
    surfaceContainer = Color(0xFF2E3138),
    surfaceContainerHigh = Color(0xFF363B44),
    surfaceContainerHighest = Color(0xFF3F4450),
    outline = Color(0xFFAFB2BB),
    error = Color(0xFFFFD2CC),
    onError = Color(0xFF540003),
    errorContainer = Color(0xFFFF5449),
    onErrorContainer = Color(0xFF000000)
)

val SlateLightColorScheme = lightColorScheme(
    primary = Color(0xFF47617A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCBE6FF),
    onPrimaryContainer = Color(0xFF001E31),
    secondary = Color(0xFF546070),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD8E4F5),
    onSecondaryContainer = Color(0xFF111C29),
    tertiary = Color(0xFF6B5778),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFF1DBFF),
    onTertiaryContainer = Color(0xFF251432),
    background = Color(0xFFE6E8EB),
    onBackground = Color(0xFF191C1E),
    surface = Color(0xFFE6E8EB),
    onSurface = Color(0xFF191C1E),
    surfaceVariant = Color(0xFFCCD3D9),
    onSurfaceVariant = Color(0xFF41474D),
    surfaceDim = Color(0xFFA5B0C0),
    surfaceBright = Color(0xFFF1F2F3),
    surfaceContainerLowest = Color(0xFFFAFAFA),
    surfaceContainerLow = Color(0xFFD7DAE0),
    surfaceContainer = Color(0xFFCBD0D8),
    surfaceContainerHigh = Color(0xFFBEC5CF),
    surfaceContainerHighest = Color(0xFFB2BBC7),
    outline = Color(0xFF71787E),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002)
)

val SlateDarkColorScheme = darkColorScheme(
    primary = Color(0xFFAFCAE6),
    onPrimary = Color(0xFF15334A),
    primaryContainer = Color(0xFF2E4A62),
    onPrimaryContainer = Color(0xFFCBE6FF),
    secondary = Color(0xFFBCC8DA),
    onSecondary = Color(0xFF263240),
    secondaryContainer = Color(0xFF3C4857),
    onSecondaryContainer = Color(0xFFD8E4F5),
    tertiary = Color(0xFFD7BEE4),
    onTertiary = Color(0xFF3B2947),
    tertiaryContainer = Color(0xFF523F5E),
    onTertiaryContainer = Color(0xFFF1DBFF),
    background = Color(0xFF1F2428),
    onBackground = Color(0xFFE1E2E5),
    surface = Color(0xFF1F2428),
    onSurface = Color(0xFFE1E2E5),
    surfaceVariant = Color(0xFF33383D),
    onSurfaceVariant = Color(0xFFC0C7CD),
    surfaceDim = Color(0xFF1A1E21),
    surfaceBright = Color(0xFF4B545A),
    surfaceContainerLowest = Color(0xFF14171A),
    surfaceContainerLow = Color(0xFF252B30),
    surfaceContainer = Color(0xFF2E353B),
    surfaceContainerHigh = Color(0xFF383F45),
    surfaceContainerHighest = Color(0xFF414950),
    outline = Color(0xFF8B9198),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6)
)
